awesomeWM/awesome-www

Makefile

I was getting this error:
> Scanning dependencies of target ldoc
> make[5]: Leaving directory '/home/user/Vcs/awesome-www/src/.build-host.example.com-x86_64-pc-linux-gnu-6.1.1'
> make[5]: Entering directory '/home/user/Vcs/awesome-www/src/.build-host.example.com-x86_64-pc-linux-gnu-6.1.1'
> lua: cannot open /dev/null/Vcs/ldoc/ldoc.lua: Not a directory
With this custom `ldoc` wrapper:
> lua ~/Vcs/ldoc/ldoc.lua $*

Makefile: use original HOME with ldoc target

---

templates/page.tmpl

This way the links will keep pointing to the old server even if we
redirect our server elsewhere.
CC @blueyed

Use complete URLs for old issues and wiki

---

templates/page.tmpl

piwik.awesomewm.org points at cname-piwik.thequod.de, which is my
personal [Piwik](http://piwik.org/) instance.  The redirection through the subdomain is used
to make this look like a non-third-party service.
TODO:

Add tracking code for Piwik

---

download.mdwn

What better way is there to bloat a git repository than importing binary
data? :-)
Fixes: #26
Signed-off-by: Uli Schlachter psychon@znc.in
Fun fact: First git push took 12 minutes. I screwed something up and had to re-do it. Second push finished in just 10 minutes! `du -sh download` says this commit is adding 58MB (or MiB? Dunno) of binary data.

Import all the old releases

---

.travis.yml

The build after merging #38 failed: https://travis-ci.org/awesomeWM/awesome-www/builds/186631479
It looks like `git show --stat` started a pager and then Travis eventually terminated the build. This is just a theory, but using `--no-pager` won't hurt.
Edit: I guess `dist: trusty` brought a newer git and that's what eventually caused this?

.travis.yml: Use --no-pager

---

doing_a_release.mdwn

This page is described on the old document that was available on the
wiki. However, I updated it to the new state of things and, for example,
left out the mailing list. This means that lots of the things here are
new and untested, but I guess they will be tested soon.
That's it with my time for today. Sorry, but your Christmas present will have to wait until tomorrow (but only if you are good and merge all my pull requests ;-) ).
Of course, feel free to point out possible improvements before I do something wrong!

Add a doing_a_release page

---

local.css

When you hover over one of the items in the top menu, e.g. "home", a
background appears. This commit changes this background to cover the
full height of the top-menu instead of only a small rectangle around the
item.
The "margin: 0px" is needed so that this background can "reach" up to
the top of the page. Note that this however also affects other elements
on the page and now the "awesome" at the top left of the page is a bit
farther up.
The height of "#top" and the padding around the links then change the
actual height of this background.
This is partial revert of 34c806d8176a87398e2372.
For me locally, before (top) and after (bottom) (yes, I don' t have perlmagick installed; i know):

Change the appearance of the top-menu

---

Makefile
download.mdwn

This is required for GitHub pages to use a proper mime type.
Fixes https://github.com/awesomeWM/awesome-www/issues/51.

Add .txt extenstion to changelogs

---

README.md

There were some spacing mistakes in the Screenshot contributing section from README, those mistakes has been fixed here.

Fixing wrong Markdown from README

---

templates/page.tmpl

Ref: https://github.com/awesomeWM/awesome-www/issues/64

menu: remove direct link to apidoc, shorten "doc"

---

recipes/xrandr.mdwn

As ikiwiki creates a folder for each file, the current path for `xrandr.lua` has an extrar `/xrandr`, so this PR fix it.

Fix xrandr.lua link

---

recipes/xrandr.mdwn

It is my understanding that [title](target) is meant for external links
while [[title|target]] does internal links. The main difference here is
that ikiwiki automatically finds the target and makes it work with its
directory structure, so that no "manual ../" is needed.
This amends/fixes commit f9e7311e.
CC @aajjbb @blueyed Just FYI. (Also, I think it's a bit easier to understand this way).
Oh and according to `diff`, the generated html stays the same.

Fix "fix xrandr.lua link"

---

recipes/xrandr.lua

The last changes on the iteration process made `xrandr.lua` not cycle through screen configurations. This PR fixes it.

Making xrandr.lua cycle through states

---

recipes/xrandr.lua

This removes some useless font and icon shuffling and uses naughty's destroy callback instead of having its own timer to do this. This has a behaviour change: If you click on the naughty notification, the change is not applied and you stay with the current configuration. Only if you let this actually expire does it apply the change.

More XrandR changes

---

recipes.mdwn
recipes/countdown.mdwn

As title says, this is a countdown widget. It consists in a clickable checkbox (left - set time, right - stop) and a textbox showing the countdown.
Original source is [here](https://github.com/copycat-killer/lain/pull/249), but it's more visible (and maybe useful to some) on the site.

recipes: add countdown widget

---

recipes.mdwn
recipes/watch.mdwn

`awful.widget.watch` was introduced in 4.0, and since 4.1 it also returns the timer.
This makes my `lain.widget.watch` redundant, so I'd like to move my [use case examples](https://github.com/copycat-killer/lain/wiki/watch#use-case-examples) to the website, where they can have some visibility.

awful.util.watch: add some use case examples

---

Makefile
README.for_webpage.md

Fixes: https://github.com/awesomeWM/awesomeWM.github.io/issues/4
The generated README should look as follows: https://github.com/psychon/awesome-www/blob/4b23d5fb1484ddf29942390990c6aa904dbd8dc2/README.for_webpage.md
Edit: I just found https://github.com/awesomeWM/awesomeWM.github.io/pull/2/commits/a48ba66a0d4ebcf2bab240b1eb730aeac94b76a5. Is that README better than mine?

Add a README.md to the generated web page

---

download.mdwn

See the recent problems with broken LGI installations for reasons why.
CC @Elv13 @blueyed 
----
Another (additional) idea: i3 offers a repository for debian and ubuntu with their latest version: http://i3wm.org/docs/repositories.html
I did not look too closely yet, but these images [seem to be built on travis](https://github.com/i3/i3/blob/86ad867277b0de63537720ec49ca6523707660cb/.travis.yml#L38-L41) and then [deployed to bintray](https://github.com/i3/i3/blob/86ad867277b0de63537720ec49ca6523707660cb/.travis.yml#L46-L62) (whatever that is...).
We could do the same thing, but might have to ship packages for more than just awesome. Currently for Travis on [Ubuntu Trusty](https://github.com/awesomeWM/awesome-www/blob/master/.travis.yml#L1) we "just" need [libxcb-cursor-dev, xcb-util-xrm and …

Recommend using distro packages

---

recipes.mdwn

@psychon suggested in https://github.com/stefano-m/awesome-pulseaudio_widget/issues/1#issue-241511660 that I add my PulseAudio widget to the recipes page.
I have also added two more widgets written by me: Connman network manager and Battery Indicator (uses UPower).
All widgets are available from [my luarocks.org modules](http://luarocks.org/modules/stefano-m) too.

Add Pulseaudio, Connman and Battery to Widgets recipes

---

download.mdwn

Just linking to gobolinux.org without `https://` brung up a 404. This PR fixes that :P

download: Fix GoboLinux link

---

recipes/.luacheckrc

This uses awesome's .luacheckrc for recipes also.
In the long run we might want to enforce luacheck for recipes, but
currently there are quite some issues still.
```
% luacheck recipes
Checking recipes/gpmdp.lua                        28 warnings
recipes/gpmdp.lua:21:21: accessing undefined variable dpi
recipes/gpmdp.lua:34:91: unused argument stdout
recipes/gpmdp.lua:71:5: setting non-standard global variable gpm_now
recipes/gpmdp.lua:74:9: mutating non-standard global variable gpm_now
recipes/gpmdp.lua:75:9: mutating non-standard global variable gpm_now
recipes/gpmdp.lua:77:9: setting non-standard global variable dict
recipes/gpmdp.lua:77:15: setting non-standard global variable pos
recipes/gpmdp.lua:77:20: setting non-standard global variable err
recipes/gpmdp.lua:79:9: mutating …
```

Recipes: add .luacheckrc symlink

---

recipes/mpc.lua

If the host name begins with a slash then we assume that it is a unix
socket. Else, we use a TCP connection as before.

mpc.lua: Add support for Unix sockets

---

recipes/watch.mdwn

A disk I/O widget using `iostat` from `sysstat` utilities. Taken from [here](https://github.com/lcpz/lain/issues/364#issuecomment-333805465).

Recipes: add iostat

---

index.mdwn

Remove accidental period and separate consecutive adjectives with comma

Grammar fixes

---

README.md

mdl complained about it:
README.md:24: MD046 Code block style
A detailed description of the rules is available at
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

Fix code block in README

---

index.mdwn

This commit removes the "News" section on the front page. This
effectively reverts commit 3e8fadcb747e2bd0247 from two years ago.

AwesomeWM v4.0 is no longer breaking news

---

Makefile

This allows to run it locally more easily.

Makefile: improve build_for_travis

---

recipes/gpmdp.lua

In current condition recipe for google music desktop just dies without any exception shown.  
Not sure if I've done it right, but I think this PR will at least make this widget work.

gpmdp.lua: simple fixes to make it work in 2019

---

recipes.mdwn

I'd like to add [modalawesome](https://github.com/potamides/modalawesome), a framework for modal, vi-like keybindings,  to the recipes section. I think the exposure on the website could be of interest to some awesome users, who also like modal editors. Here is a short excerpt from the projects README:
>Modalawesome makes it possible to create vi-like keybindings for the [awesome window manager](https://awesomewm.org/). It introduces a modal alternative to the standard [awful.key](https://awesomewm.org/doc/api/libraries/awful.key.html) keybindings and supports complex commands with motions and counts by making use of Lua [patterns](https://www.lua.org/manual/5.3/manual.html#6.4.1). Check out the [demo](https://v.redd.it/e4pzh8l53df51/DASH_1080.mp4) to get an overall impression of what this …

recipes: add modalawesome

---

recipes.mdwn
recipes/wirelessStatus.lua
recipes/wirelessStatus.mdwn

Adding a simple wireless status widget/watcher.
I think that everything should be OK except code blocks are messed up:
I don't know if this is only my problem because it goes the same for other recipes.

Adding wireless status widget/watcher

---

recipes/mpc.mdwn

Found a minor misspelling. "fined" should be "found".

Fixed minor misspelling

---

download.mdwn

Replace broken (returns HTTP 404) Fedora package download link:
https://apps.fedoraproject.org/packages/awesome
with:
https://packages.fedoraproject.org/pkgs/awesome/awesome/.

Fix broken Fedora package link

---

download.mdwn

Fix broken arch package link after the [git migration](https://archlinux.org/news/git-migration-announcement/)

Fix arch package broken link
