awesomeWM/awesome-www

download.mdwn

Markdown typo (`)

---

templates/page.tmpl

See https://www.openhub.net/p/awesome/widgets for a list of available openhub widgets.
Without this the widgets are not loaded on https://awesomewm.org.

Use https for flattr and ohloh/openhub widgets; update them

---

download.mdwn

- fix section headers
- link to Arch packages

Improve Download page

---

.travis.yml
Makefile

Based on https://github.com/psychon/awesome-www/tree/travis.

Travis integration

---

.travis.yml

Fixes https://github.com/awesomeWM/awesome-www/issues/13.

Travis: install perlmagick for ikiwiki

---

Makefile

Ref: https://github.com/awesomeWM/awesome-www/pull/12#issuecomment-219466960.

ikiwiki: --url is not required, since we are not using --rss / blogs

---

download.mdwn
releases.mdwn

This list was taken from our Mediawiki instance and converted into the ikiwiki syntax.

Add a page listing old releases

---

community.mdwn
doc.mdwn

Remove remaining links to the wiki

---

community.mdwn
download.mdwn

Bring more content up to date. This kind of make the Reddit and StackOverflow communities official. Given the mailing list will close and IRC almost dead, we need an official place for questions.

Improve download

---

.travis.yml

This installs all needed dependencies for the next release. Hopefully we
will just have to update the subproject commit then.

Prepare .travis.yml for next release

---

download.mdwn

Ref: https://github.com/awesomeWM/awesome/pull/1286.

Download: link to GPG signatures

---

doing_a_release.mdwn

The list missed one of the files which should have changes and you can
only verify that the links are working after the web page was updated.

Fix some small issues in doing_a_release.mdwn

---

community.mdwn

Community page update

---

Makefile

This changes the Makefile so that old files are deleted. I expect quite a number of files to go away when this is merged. :-)

Delete old / unneeded files

---

community.mdwn

community: Add hints on how to change the web page

---

recipes.mdwn
templates/page.tmpl

Hi, the goal of this new recipes section is to be a home for the ones who miss the wiki. The goal here is to post config files, different widgets and other awesome related stuff (similarly with the old wiki, but better organized, as new content is received as pull requests).

Adding a recipes section

---

index.mdwn
local.css
templates/page.tmpl

Fixing all HTML issues pointed by [https://validator.nu](https://validator.nu)

Fixing HTML issue.

---

doc.mdwn
index.mdwn
local.css

Fixes https://github.com/awesomeWM/awesome-www/issues/69.

Add standout section on the homepage and v4 doc section

---

recipes.mdwn
recipes/mpc.lua
recipes/mpc.mdwn

@Elv13 wanted me to add this to the recipes section. Suggestions for further improvements welcome. I did a quick test of this and it actually works. ;-)
Compared to other implementations that I saw, I think I deserve bonus points for not using `io.popen("mpc")`. Further bonus points for being asynchronous.
Edit: I don't want to, but do I have to add a screenshot of this? I would say that the result is quite boring, but others might disagree
Edit: With the above I mean "add a screenshot of the resulting widget to the page" and not what I did in the next comment where I made a screenshot of the web page.

Add a recipe for an MPD widget

---

recipes/mpc.lua
recipes/mpc.mdwn

This fixes a bug that made the code fail to detect disconnects. The rest is some other small-ish changes.

Some small-ish MPC stuff

---

recipes.mdwn

Adding Elv13 custom libraries to the recipes section

adding Elv13 libraries to recipes

---

doing_a_release.mdwn

Fix a small oversight in doing_a_release.mdwn

---

recipes.mdwn

https://github.com/raksooo/poppin

Added poppin' to recipes

---

recipes.mdwn

Ref: https://github.com/blueyed/awesome-cyclefocus/issues/12

recipes: add awesome-cyclefocus

---

index.mdwn

Ref: https://github.com/awesomeWM/awesome/issues/598

Update the supported multiscreen modes

---

recipes.mdwn
recipes/gpmdp.lua
recipes/gpmdp.mdwn

Moved lain.widget.contrib.gpmdp out of lain and into a recipe.
https://github.com/copycat-killer/lain/pull/354

add gpmdp recipe

---

Makefile

awesome: build is now a directory, not a symlink

---

.travis.yml
README.md

Integrate markdownlint

---

index.mdwn

I hereby put my changes under CC0. Share and enjoy!

Correct some awkward grammar.

---

templates/page.tmpl

update footer Copyleft date

---

recipes.mdwn

https://github.com/raksooo/screenrotation

Added screen rotation recipe

---

recipes.mdwn

It has been turned into an organization [1].
1: https://github.com/vicious-widgets/vicious/issues/60

docs: update URL for vicious

---

local.css

So the text uses the color defined by the teme like the background-color already does

fix font color on navigators with custom theme

---

recipes.mdwn

Add `layout-machi` to the recipes for more visibility.
Please see the intro post [here](https://www.reddit.com/r/awesomewm/comments/cbzbi7/layoutmachi_a_manual_layout_with_interactive/).

recipes: add layout-machi

---

recipes.mdwn

Not my blog, this guide is a useful resource for beginners, so I add it here as asked [on Reddit](https://old.reddit.com/r/awesomewm/comments/il6tyy/a_comprehensive_guide_to_awesomewm/g3qvunc/)
I would like to add [epsi-rns](https://github.com/epsi-rns) as a reviewer for his approval, but I don't ~find the option~ have the rights.

Add Epsi guide to the recipes

---

recipes.mdwn
recipes/mic.lua
recipes/mic.mdwn

Adding a simple microphone widget/watcher.
I think that everything should be OK except code blocks are messed up:
I don't know if this is only my problem because it goes the same for other recipes.

Adding microphone watcher/widget

---

recipes/watch.mdwn

A simple volume widget for pure Pipewire systems.

Adding Pipewire watch recipe

---

recipes.mdwn

add my [dotfiles](https://github.com/rxyhn/dotfiles) into theme recipes

add rxyhn's dotfiles into theme recipes
